name: Job Setup
description: Reusable action to set up the working directory of the current job

runs:
    using: composite
    steps:
        - name: Use Node.js v20
          uses: actions/setup-node@v4
          with:
              node-version: '20.x'
              cache: 'npm'
        - name: Install dependencies from cache
          shell: bash
          run: 'npm clean-install --prefer-offline'
