---
name: Job Setup
description: Reusable action to set up the working directory of the current job

runs:
    using: composite
    steps:
        - name: Use Node.js v${{ matrix.node-version }}
          uses: actions/setup-node@v6
          with:
              node-version: ${{ matrix.node-version }}
              cache: "npm"
        - name: Install dependencies from cache
          shell: bash
          run: "npm clean-install --prefer-offline"
