export const zodMutationCategories = [
    'primitive',
    'presence',
    'readonly',
    'object',
    'string',
    'number',
    'collection',
    'union',
    'fallback',
    'coercion'
] as const;

export type ZodMutationCategory = typeof zodMutationCategories[number];

export const zodMutationOperators = [
    'ZodPrimitiveFactorySwap',
    'ZodOptionalAdd',
    'ZodOptionalRemove',
    'ZodNullableAdd',
    'ZodNullableRemove',
    'ZodNullishRemove',
    'ZodNullishToNullable',
    'ZodNullishToOptional',
    'ZodNonoptionalRemove',
    'ZodReadonlyAdd',
    'ZodReadonlyRemove',
    'ZodObjectPolicyAdd',
    'ZodObjectPolicyRemove',
    'ZodObjectFactorySwap',
    'ZodObjectCatchallRemove',
    'ZodObjectFieldRemove',
    'ZodObjectFieldOptionalAdd',
    'ZodObjectFieldNullableAdd',
    'ZodStringCheckRemove',
    'ZodStringBoundaryChange',
    'ZodStringFormatToString',
    'ZodNumberCheckRemove',
    'ZodNumberBoundaryChange',
    'ZodNumberStrictnessSwap',
    'ZodCollectionCheckRemove',
    'ZodCollectionBoundaryChange',
    'ZodArrayToTuple',
    'ZodTupleToArray',
    'ZodTupleItemRemove',
    'ZodTupleRestAdd',
    'ZodTupleRestRemove',
    'ZodRecordFactorySwap',
    'ZodUnionOptionRemove',
    'ZodEnumValueRemove',
    'ZodNumericLiteralChange',
    'ZodFallbackRemove',
    'ZodCustomBehaviorRemove',
    'ZodCoercionRemove'
] as const;

export type ZodMutationOperator = typeof zodMutationOperators[number];

export const zodMutationOperatorCategories: Record<ZodMutationOperator, ZodMutationCategory> = {
    ZodPrimitiveFactorySwap: 'primitive',
    ZodOptionalAdd: 'presence',
    ZodOptionalRemove: 'presence',
    ZodNullableAdd: 'presence',
    ZodNullableRemove: 'presence',
    ZodNullishRemove: 'presence',
    ZodNullishToNullable: 'presence',
    ZodNullishToOptional: 'presence',
    ZodNonoptionalRemove: 'presence',
    ZodReadonlyAdd: 'readonly',
    ZodReadonlyRemove: 'readonly',
    ZodObjectPolicyAdd: 'object',
    ZodObjectPolicyRemove: 'object',
    ZodObjectFactorySwap: 'object',
    ZodObjectCatchallRemove: 'object',
    ZodObjectFieldRemove: 'object',
    ZodObjectFieldOptionalAdd: 'object',
    ZodObjectFieldNullableAdd: 'object',
    ZodStringCheckRemove: 'string',
    ZodStringBoundaryChange: 'string',
    ZodStringFormatToString: 'string',
    ZodNumberCheckRemove: 'number',
    ZodNumberBoundaryChange: 'number',
    ZodNumberStrictnessSwap: 'number',
    ZodCollectionCheckRemove: 'collection',
    ZodCollectionBoundaryChange: 'collection',
    ZodArrayToTuple: 'collection',
    ZodTupleToArray: 'collection',
    ZodTupleItemRemove: 'collection',
    ZodTupleRestAdd: 'collection',
    ZodTupleRestRemove: 'collection',
    ZodRecordFactorySwap: 'collection',
    ZodUnionOptionRemove: 'union',
    ZodEnumValueRemove: 'union',
    ZodNumericLiteralChange: 'union',
    ZodFallbackRemove: 'fallback',
    ZodCustomBehaviorRemove: 'fallback',
    ZodCoercionRemove: 'coercion'
};
